import test from 'node:test';
import assert from 'node:assert/strict';
import { cp, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createLauncherServer } from '../../../tools/launcher/server.mjs';
import { createLock } from '../../../scripts/runtime/index.mjs';
import { workspace, samplePackage, environment, until, json, save, ROOT } from './helpers.mjs';
test('COMPLETION-HTTP template distribution and static instantiation followed by reviewed real upgrade and full data rollback', { timeout: 180000 }, async t => {
  const app = await workspace(t), directory = await samplePackage(app), server = await createLauncherServer({ root: app.root, ...environment }); app.cleanups.push(() => server.close());
  const call = async (path, body, expected = 200) => { const response = await fetch(new URL(path, server.url), { method: body === undefined ? 'GET' : 'POST', headers: { authorization: 'Bearer ' + server.token, 'x-csrf-token': server.csrfToken, 'content-type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); const data = await response.json(); assert.equal(response.status, expected, JSON.stringify(data)); return data; };
  const finish = result => until(async () => { const value = (await call('/api/operations/' + result.operationId)).operation; if (value.state === 'running') return false; assert.equal(value.state, 'succeeded', JSON.stringify(value)); return value.result; }, { timeoutMs: 100000 });
  const declaration = await json(join(ROOT, 'docs/ecosystem/template.example.json')), template = join(app.directory, 'template');
  await finish(await call('/api/templates/create', { directory, template: declaration, destination: template, redistributionAcknowledged: true }, 202));
  const inspected = await call('/api/templates/inspect', { directory: template }); assert.equal(inspected.inspection.startsModules, false);
  const review = await call('/api/templates/preview', { directory: template, values: { 'initial-text': 'HTTP 模板 🌍', 'source-topic': 'template/http/source' } });
  await call('/api/templates/instantiate', { previewId: review.previewId, destination: join(app.directory, 'generated'), redistributionAcknowledged: false }, 409);
  await call('/api/templates/instantiate', { previewId: review.previewId, destination: join(app.directory, 'generated'), redistributionAcknowledged: true, values: {} }, 400);
  const generated = await finish(await call('/api/templates/instantiate', { previewId: review.previewId, destination: join(app.directory, 'generated'), redistributionAcknowledged: true }, 202));
  await call('/api/templates/instantiate', { previewId: review.previewId, destination: join(app.directory, 'replay'), redistributionAcknowledged: true }, 409);
  assert.equal(generated.requiresNewExecutionReview, true); assert.equal(generated.pack.components[0].settings.text, 'HTTP 模板 🌍');
  const importedReview = await call('/api/review', { directory: generated.directory }); await call('/api/instances', { reviewId: importedReview.reviewId, instanceId: 'sample' });
  const executionReview = await call('/api/instances/sample/review', {}); const running = await finish(await call('/api/instances/sample/start', { reviewId: executionReview.reviewId, accepted: true }, 202)); app.observe(running.status);
  const analyzed = await fetch(new URL('/analyze', running.links.entryUrl), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text: '真实升级前 🌍' }) }); assert.equal(analyzed.status, 200);
  const statePath = join(running.directory, 'programs/source/source.json');
  const policies = ['source', 'stats', 'desk'].map(componentId => ({ componentId, mode: 'preserve', dataFormat: 'provider-defined-v1' }));
  const candidate = join(app.directory, 'candidate'); await cp(generated.directory, candidate, { recursive: true }); const manifest = await json(join(candidate, 'pack.json')); manifest.version = '9.0.0'; await save(join(candidate, 'pack.json'), manifest); await createLock(candidate, environment);
  await call('/api/instances/sample/upgrade-plan', { candidate, statePolicies: policies }, 409);
  await finish(await call('/api/instances/sample/stop', {}, 202)); const originalState = await readFile(statePath);
  const upgrade = await call('/api/instances/sample/upgrade-plan', { candidate, statePolicies: policies }); await call('/api/instances/sample/upgrade', { previewId: upgrade.previewId, accepted: false }, 409);
  const upgraded = await finish(await call('/api/instances/sample/upgrade', { previewId: upgrade.previewId, accepted: true }, 202)); assert.equal(upgraded.instance.pack.version, '9.0.0'); assert.equal(upgraded.requiresNewExecutionReview, true);
  await assert.rejects(server.manager.start('sample', executionReview.reviewId, true), { code: 'REVIEW_REQUIRED' });
  const rollback = await call('/api/instances/sample/rollback-plan', { transactionId: upgraded.transactionId }); assert.equal(rollback.preview.discardsCurrentData, true);
  const restored = await finish(await call('/api/instances/sample/rollback-upgrade', { previewId: rollback.previewId, accepted: true }, 202)); assert.equal(restored.instance.pack.version, generated.pack.version); assert.deepEqual(await readFile(statePath), originalState);
  const history = (await call('/api/instances/sample/upgrade-history')).history; assert.equal(history.transactions.find(transaction => transaction.transactionId === upgraded.transactionId).state, 'rolled-back');
  const probe = await call('/api/isolation/probe', { dockerPath: process.execPath, endpoint: process.platform === 'win32' ? 'npipe:////./pipe/dockerDesktopLinuxEngine' : 'unix:///var/run/docker.sock' }); assert.equal(probe.probe.available, false);
  await call('/api/review', { directory: generated.directory, isolation: { dockerPath: process.execPath, endpoint: 'unix:///var/run/docker.sock', image: 'node@sha256:' + 'a'.repeat(64) } }, 422);
  app.record('template-upgrade-rollback-through-authenticated-http', { generated: generated.directory, transactionId: upgraded.transactionId, currentDataRestored: true, sandboxProbe: probe.probe.available });
});
